// Generated by CoffeeScript 1.6.3
var Website;

Website = Website || {};

Website.apps = {
  dataMenu: (function() {
    'use strict';
    var JSONObj;
    JSONObj = {
      "menu": [
        {
          'text': 'Blog',
          'url': 'http://imarcker.blogspot.com'
        }, {
          'text': 'GitHub',
          'url': 'http://github.com/marcker'
        }, {
          'text': 'Facebook',
          'url': 'http://facebook.com/imarcker'
        }, {
          'text': 'Google Plus',
          'url': 'https://plus.google.com/102852478914643331562'
        }, {
          'text': 'Valid HTML',
          'url': 'http://validator.w3.org/check?uri=http://marcker.net'
        }, {
          'text': 'Valid CSS',
          'url': 'http://jigsaw.w3.org/css-validator/validator?uri=http://marcker.net'
        }
      ]
    };
    return JSONObj;
  })(),
  createHTML: function(container, id) {
    'use strict';
    var div, ul;
    div = document.querySelector(container);
    ul = document.createElement('ul');
    ul.setAttribute('id', id);
    div.appendChild(ul);
    return ul;
  },
  populate: function(container) {
    'use strict';
    var a, elem, i, li, ul, _i, _len, _ref;
    ul = this.createHTML(container, 'dropdown-menu');
    a = [];
    li = [];
    _ref = this.dataMenu.menu;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = _i += 1) {
      elem = _ref[i];
      li[i] = document.createElement('li');
      a[i] = document.createElement('a');
      a[i].setAttribute('href', this.dataMenu.menu[i].url);
      a[i].setAttribute('title', this.dataMenu.menu[i].text);
      a[i].innerHTML = this.dataMenu.menu[i].text;
      li[i].appendChild(a[i]);
      ul.appendChild(li[i]);
    }
    return ul;
  },
  github: function(response) {
    'use strict';
    var JSONObj, date, elem, i, list, updates, _i, _len;
    JSONObj = response.data;
    updates = document.querySelector('.updates');
    list = '';
    date = [];
    for (i = _i = 0, _len = JSONObj.length; _i < _len; i = _i += 1) {
      elem = JSONObj[i];
      if (JSONObj[i].type === 'PushEvent') {
        date[i] = new Date(JSONObj[i].created_at);
        list += '<li>' + date[i].getDate() + '/' + (date[i].getMonth() + 1) + '/' + date[i].getFullYear() + '&raquo; <a class="commit" href="' + JSONObj[i].payload.commits[0].url + '">' + JSONObj[i].payload.commits[0].message + '</a> &#8594; ' + '<a class="repo" href="' + JSONObj[i].repo.url + '">' + JSONObj[i].repo.name + '</a></li>';
      }
    }
    updates.innerHTML = list;
  }
};

Website.apps.populate('#nav');
